name: Java CI
on:
  push:
    branches: [main]
jobs:
  test:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
        java-version: '11'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

